export interface Expedientes {
    Id:number,
    ServicioAtencionId: number,
    Cliente: string,
    Correo:string,
    Direccion: string,
    DireccionDestino: string,
    Pais: string,
    Ciudad: string,
    Colonia: string,
    NombreAdicional: string,
    NombreCorredor?: string,
    RefPlanId: number,
    PolizaExterna: string,
    NombreConvenio: string,
    Plan: string,
    Zona: string,
    Taller?: string,
    TelefonoAdicional: string,
    TelefonoOrigen: string,
    TelefonoReportante: string,
    Observaciones: string,
    RefGestorId: number,
    Nombre: string,
    RefProveedorId: number,
    RefDepartamentoId: number,
    NombreProveedor: string,
    NombreAgente: string,
    TipoAgente: string,
    FechaRegistro: Date,
    Servicio: string,
    NombreCategoria: string,
    IdAjusteAudiencia: number,
    AgendarAudiencia: number,
    AseguradoUsoPoliza: number,
    Blindado: string,
    ColorVehiculo: string,
    ConductorAfiliado: string,
    ConductorDetenido: string,
    DanioFrontal: string,
    DanioLataralIzquierdo: string,
    DanioLateralDerecho: string,
    DanioTrasero: string,
    VersionAsegurado: string,
    DescripcionAudiencia: string,
    AnalisisAsesorEmergencia: string,
    DescripcionTercerosHeridos: string,
    DescripcionTercerosMuertos: string,
    DañosVehiculo: string,
    FechaHora: string,
    IdPais:number,
    FechaRegistroAjuste: Date,
    IdentidaConductor: string,
    LesionadosSinAudiencia: number,
    LugarAudiencia: string,
    MarcaVehiculo: string,
    ModeloVehiculo: string,
    ChasisVehiculo: string,
    PlacaVehiculo: string,
    AnioVehiculo: string,
    NombreAsegurado: string,
    NombreConductor: string,
    Poliza: string,
    ObservacionTaller: string,
    RefProveedorAgenteAbogadoId: number,
    RefProveedorAgenteId: number,
    TerceroResponsable: number,
    TercerosMuertos: string,
    VehiculoDetenido: string,
    VehiculoVolcado: string,
    IdAjustador: number,
    Year: number,
    Modelo: string,
    NumeroPlaca: string,
    Color: string,
    Chasis: string,
    Motor: number,
    Marca: string,
    Tipo_Vehiculo:string,
    Ramo: string,
    LatitudCliente:any,
    LongitudCliente:any,
    Moneda:any
}
