export const Predeterminados = [
    {nombre: 'AgendarAudiencia', valor: 2},
    {nombre: 'IdPais', valor: 3},
    {nombre: 'Sexo', valor: 1},
    {nombre: 'RefProveedorAgenteAbogadoId', valor: 0},
    {nombre: 'AseguradoUsoPoliza', valor: 1},
    {nombre: 'TerceroResponsable', valor: 1},
    {nombre: 'LesionadosSinAudiencia', valor: 0},
    {nombre: 'ConductorAfiliado', valor: 1},
    {nombre: 'ConductorDetenido', valor: 2},
    {nombre: 'VehiculoDetenido', valor: 2},
    {nombre: 'TercerosHeridos', valor: 2},
    {nombre: 'TercerosMuertos', valor: 2},
    {nombre: 'DanioFrontal', valor: 2},
    {nombre: 'DanioTrasero', valor: 2},
    {nombre: 'DanioLateralDerecho', valor: 2},
    {nombre: 'DanioLataralIzquierdo', valor: 2},
    {nombre: 'VehiculoVolcado', valor: 2},
    {nombre: 'FechaHora', valor: new Date().toISOString()},
    {nombre: 'Blindado', valor: 2},
    {nombre: 'Latitud', valor: localStorage.getItem('laLatitud')},
    {nombre: 'Longitud', valor: localStorage.getItem('laLongitud')},
    {nombre: 'RefTipoConductorId', valor: 1},
    {nombre: 'RefTipoLicenciaId', valor: 2},
    {nombre: 'PruebaAlcoholemia', valor: 2},
    {nombre: 'RefTipoCombustibleId', valor: 1},
    {nombre: 'AC', valor: 1},
    {nombre: 'Rines', valor: 2},
    {nombre: 'BolsaAire', valor: 1},
    {nombre: 'CierreCentralizado', valor: 1},
    {nombre: 'Mecanico', valor: 1},
    {nombre: 'RetrovisorElectronico', valor: 2},
    {nombre: 'Overfenders', valor: 2},
    {nombre: 'ColaPato', valor: 2},
    {nombre: 'CintaDecorativa', valor: 2},
    {nombre: 'LicenciaEstado', valor: 0},
    {nombre: 'RefTipoSolicitanteInformeAjusteId', valor: 1},
    {nombre: 'CulpableCompromisoPago', valor: 1},
    {nombre: 'Kilometraje', valor: 0},
    {nombre: 'RefMunicipioId', valor: 0}
]

export const datosAtencionKeys = [
        {nombre: 'IdAtencion'},
        {nombre: 'PolizaPS'},
        {nombre: 'PolizaExterna'},
        {nombre: 'Plan'},
        {nombre: 'Certificado'},
        {nombre: 'RefIdentificacionTipo'},
        {nombre: 'IdentidadCliente'},
        {nombre: 'TelefonoOrigen'},
        {nombre: 'Cliente'},
        {nombre: 'RefTipoServicioId'},
        {nombre: 'FechaInicio'},
        {nombre: 'FechaFin'},
        {nombre: 'RefAgenteId'},
        {nombre: 'RefProveedorId'},
        {nombre: 'RefClienteId'},
        {nombre: 'RefEstadoId'},
        {nombre: 'CiudadId'},
        {nombre: 'RefColoniaId'},
        {nombre: 'FechaPagoCliente'},
        {nombre: 'IdPoliza'},
        {nombre: 'Direccion'},
        {nombre: 'ObservacionesAtencion'},
        {nombre: 'LatitudCliente'},
        {nombre: 'LongitudCliente'},
        {nombre: 'RefGestorId'},
        {nombre: 'TiempoMaximoEspera'},
        {nombre: 'IdEstadoAtencion'},
        {nombre: 'LbEstado'},
        {nombre: 'ColorEstado'},
        {nombre: 'LbTipoServicio'},
        {nombre: 'IdCategoriaServicio'},
        {nombre: 'IdCategoria'},
        {nombre: 'LbCategoriaServicio'},
        {nombre: 'IconClassName'},
        {nombre: 'UsuarioRegistroNombre'},
        {nombre: 'LbConvenio'},
        {nombre: 'LbPlan'},
        {nombre: 'NombreProveedor'},
        {nombre: 'Pais'},
        {nombre: 'PaisId'},
        {nombre: 'Zona'},
        {nombre: 'DireccionDestino'},
        {nombre: 'EstadoServicio'},
        {nombre: 'Ciudad'},
        {nombre: 'Colonia'},
        {nombre: 'Id'},
        {nombre: 'RefAtencionId'},
        {nombre: 'RefProveedorAgenteId'},
        {nombre: 'RefProveedorAgenteAbogadoId'},
        {nombre: 'AgendarAudiencia'},
        {nombre: 'AseguradoUsoPoliza'},
        {nombre: 'TerceroResponsable'},
        {nombre: 'LesionadosSinAudiencia'},
        {nombre: 'DescripcionAudiencia'},
        {nombre: 'RefEntidadComunicativaId'},
        {nombre: 'RefTipoAudienciaId'},
        {nombre: 'Poliza'},
        {nombre: 'Identificacion'},
        {nombre: 'Nombre'},
        {nombre: 'ConductorAfiliado'},
        {nombre: 'ConductorDetenido'},
        {nombre: 'Descripcion'},
        {nombre: 'MarcaVehiculo'},
        {nombre: 'ModeloVehiculo'},
        {nombre: 'AnioVehiculo'},
        {nombre: 'PlacaVehiculo'},
        {nombre: 'ChasisVehiculo'},
        {nombre: 'ColorVehiculo'},
        {nombre: 'VehiculoDetenido'},
        {nombre: 'DescripcionVehiculo'},
        {nombre: 'TercerosHeridos'},
        {nombre: 'TercerosMuertos'},
        {nombre: 'DescripcionTercerosHeridos'},
        {nombre: 'DescripcionTercerosMuertos'},
        {nombre: 'DanioFrontal'},
        {nombre: 'DanioTrasero'},
        {nombre: 'DanioLateralDerecho'},
        {nombre: 'DanioLataralIzquierdo'},
        {nombre: 'VehiculoVolcado'},
        {nombre: 'DescripcionDanio'},
        {nombre: 'RefPaisId'},
        {nombre: 'RefCiudadId'},
        {nombre: 'RefDeptoId'},
        {nombre: 'RefMunicipioId'},
        {nombre: 'FechaHora'},
        {nombre: 'Lugar'},
        {nombre: 'RefUsuarioId'},
        {nombre: 'FechaRegistro'},
        {nombre: 'TallerMecanicoId'},
        {nombre: 'Blindado'},
        {nombre: 'ObservacionTaller'},
        {nombre: 'ReclamoAsegurado'},
        {nombre: 'Observaciones'},
        {nombre: 'Latitud'},
        {nombre: 'Longitud'},
        {nombre: 'NombreConductor'},
        {nombre: 'IdentidaConductor'},
        {nombre: 'DPI_Pasaporte'},
        {nombre: 'TelefonoConductor'},
        {nombre: 'CelularConductor'},
        {nombre: 'Edad'},
        {nombre: 'Licencia'},
        {nombre: 'TipoLicencia'},
        {nombre: 'Vigencia'},
        {nombre: 'DireccionConductor'},
        {nombre: 'Sexo'},
        {nombre: 'RefTipoConductorId'},
        {nombre: 'NumeroReclamoFicohsa'},
        {nombre: 'DireccionEnvioCorrespondencia'},
        {nombre: 'CorreoElectronico'},
        {nombre: 'RefConducidoPorId'},
        {nombre: 'RefTipoLicenciaId'},
        {nombre: 'NombreAtribuyeAccidente'},
        {nombre: 'AutoridadInvolucrada'},
        {nombre: 'UbicacionVehiculoDetenido'},
        {nombre: 'PruebaAlcoholemia'},
        {nombre: 'RefTipoCombustibleId'},
        {nombre: 'AC'},
        {nombre: 'RInes'},
        {nombre: 'BolsaAire'},
        {nombre: 'CierreCentralizado'},
        {nombre: 'Mecanico'},
        {nombre: 'RetrovisorElectronico'},
        {nombre: 'Overfenders'},
        {nombre: 'ColaPato'},
        {nombre: 'CintaDecorativa'},
        {nombre: 'LicenciaEstado'},
        {nombre: 'RefTipoSolicitanteInformeAjusteId'},
        {nombre: 'ObservacionesFinales'},
        {nombre: 'Reserva1'},
        {nombre: 'Reserva2'},
        {nombre: 'Reserva3'},
        {nombre: 'Llantas'},
        {nombre: 'Cristales'},
        {nombre: 'TipoSiniestro'},
        {nombre: 'TipoVehiculo'},
        {nombre: 'CodigoBPMFicohsa'},
        {nombre: 'AppEstado'},
        {nombre: 'CodigoReclamoFicohsa'},
        {nombre: 'TipoAcuerdoFicohsa'},
        {nombre: 'DondeSeEncuentraVehiculo'}
]

export const ItemsExpediente = [
    {nombre: 'Id'},
    {nombre: 'RefGestorId'},
    {nombre: 'RefProveedorAgenteAbogadoId'},
    {nombre: 'PolizaExterna'},
    {nombre: 'IdentidaConductor'},
    {nombre: 'Cliente'},
    {nombre: 'Marca'},
    {nombre: 'Modelo'},
    {nombre: 'Year'},
    {nombre: 'NumeroPlaca'},
    {nombre: 'Chasis'},
    {nombre: 'Color'},
    {nombre: 'FechaRegistro'},
    {nombre: 'Direccion'},
    {nombre: 'IdPais'},
    {nombre: 'IdCiudad'},
    {nombre: 'RefDepartamentoId'},
    {nombre: 'ServicioAtencionId'},
    {nombre: 'DireccionDestino'},
    {nombre: 'Pais'},
    {nombre: 'Ciudad'},
    {nombre: 'Colonia'},
    {nombre: 'NombreAdicional'},
    {nombre: 'NombreCorredor'},
    {nombre: 'RefPlanId'},
    {nombre: 'NombreConvenio'},
    {nombre: 'Plan'},
    {nombre: 'Zona'},
    {nombre: 'Taller'},
    {nombre: 'TelefonoAdicional'},
    {nombre: 'TelefonoOrigen'},
    {nombre: 'TelefonoReportante'},
    {nombre: 'Observaciones'},
    {nombre: 'Nombre'},
    {nombre: 'RefProveedorId'},
    {nombre: 'NombreProveedor'},
    {nombre: 'NombreAgente'},
    {nombre: 'TipoAgente'},
    {nombre: 'Servicio'},
    {nombre: 'NombreCategoria'},
    {nombre: 'IdAjusteAudiencia'},
    {nombre: 'AgendarAudiencia'},
    {nombre: 'AseguradoUsoPoliza'},
    {nombre: 'Blindado'},
    {nombre: 'ColorVehiculo'},
    {nombre: 'ConductorAfiliado'},
    {nombre: 'ConductorDetenido'},
    {nombre: 'DanioFrontal'},
    {nombre: 'DanioLataralIzquierdo'},
    {nombre: 'DanioLateralDerecho'},
    {nombre: 'DanioTrasero'},
    {nombre: 'VersionAsegurado'},
    {nombre: 'DescripcionAudiencia'},
    {nombre: 'AnalisisAsesorEmergencia'},
    {nombre: 'DescripcionTercerosHeridos'},
    {nombre: 'DescripcionTercerosMuertos'},
    {nombre: 'DañosVehiculo'},
    {nombre: 'FechaHora'},
    {nombre: 'FechaRegistroAjuste'},
    {nombre: 'LesionadosSinAudiencia'},
    {nombre: 'LugarAudiencia'},
    {nombre: 'MarcaVehiculo'},
    {nombre: 'ModeloVehiculo'},
    {nombre: 'ChasisVehiculo'},
    {nombre: 'PlacaVehiculo'},
    {nombre: 'AnioVehiculo'},
    {nombre: 'NombreAsegurado'},
    {nombre: 'NombreConductor'},
    {nombre: 'Poliza'},
    {nombre: 'ObservacionTaller'},
    {nombre: 'RefProveedorAgenteId'},
    {nombre: 'TerceroResponsable'},
    {nombre: 'TercerosMuertos'},
    {nombre: 'VehiculoDetenido'},
    {nombre: 'VehiculoVolcado'},
    {nombre: 'IdAjustador'},
    {nombre: 'Motor'},
    {nombre: 'Tipo_Vehiculo'},
    {nombre: 'Ramo'},
    {nombre: 'CorreoElectronico'},
    {nombre: 'Seccion1'},
    {nombre: 'Seccion2'},
    {nombre: 'Seccion3'},
    {nombre: 'Certificado'},
    {nombre: 'TipoSiniestro'},
    {nombre: 'TipoVehiculo'},
    {nombre: 'Parentesco'},
    {nombre: 'Deducible'},
    {nombre: 'ValorReserva'},
    {nombre: 'Moneda'}

]

export const ItemsData = [
    
        {nombre: 'RefAtencionId'},
        {nombre: 'RefProveedorAgenteId'},
        {nombre: 'RefProveedorAgenteAbogadoId'},
        {nombre: 'AgendarAudiencia'},
        {nombre: 'AseguradoUsoPoliza'},
        {nombre: 'TerceroResponsable'},
        {nombre: 'LesionadosSinAudiencia'},
        {nombre: 'DescripcionAudiencia'},
        {nombre: 'Poliza'},
        {nombre: 'Identificacion'},
        {nombre: 'Nombre'},
        {nombre: 'ConductorAfiliado'},
        {nombre: 'ConductorDetenido'},
        {nombre: 'Descripcion'},
        {nombre: 'MarcaVehiculo'},
        {nombre: 'ModeloVehiculo'},
        {nombre: 'AnioVehiculo'},
        {nombre: 'PlacaVehiculo'},
        {nombre: 'ChasisVehiculo'},
        {nombre: 'ColorVehiculo'},
        {nombre: 'VehiculoDetenido'},
        {nombre: 'DescripcionVehiculo'},
        {nombre: 'TercerosHeridos'},
        {nombre: 'TercerosMuertos'},
        {nombre: 'DescripcionTercerosHeridos'},
        {nombre: 'DescripcionTercerosMuertos'},
        {nombre: 'DanioFrontal'},
        {nombre: 'DanioTrasero'},
        {nombre: 'DanioLateralDerecho'},
        {nombre: 'DanioLataralIzquierdo'},
        {nombre: 'VehiculoVolcado'},
        {nombre: 'DescripcionDanio'},
        {nombre: 'RefPaisId'},
        {nombre: 'RefCiudadId'},
        {nombre: 'RefDeptoId'},
        {nombre: 'RefMunicipioId'},
        {nombre: 'FechaHora'},
        {nombre: 'Lugar'},
        {nombre: 'RefUsuarioId'},
        {nombre: 'TallerMecanicoId'},
        {nombre: 'Blindado'},
        {nombre: 'ObservacionTaller'},
        {nombre: 'ReclamoAsegurado'},
        {nombre: 'Observaciones'},
        {nombre: 'Latitud'},
        {nombre: 'Longitud'},
        {nombre: 'NombreConductor'},
        {nombre: 'IdentidaConductor'},
        {nombre: 'DPI_Pasaporte'},
        {nombre: 'TelefonoConductor'},
        {nombre: 'CelularConductor'},
        {nombre: 'Edad'},
        {nombre: 'Licencia'},
        {nombre: 'TipoLicencia'},
        {nombre: 'Vigencia'},
        {nombre: 'DireccionConductor'},
        {nombre: 'Sexo'},
        {nombre: 'RefTipoConductorId'},
        {nombre: 'DireccionEnvioCorrespondencia'},
        {nombre: 'CorreoElectronico'},
        {nombre: 'RefTipoLicenciaId'},
        {nombre: 'NombreAtribuyeAccidente'},
        {nombre: 'AutoridadInvolucrada'},
        {nombre: 'UbicacionVehiculoDetenido'},
        {nombre: 'PruebaAlcoholemia'},
        {nombre: 'RefTipoCombustibleId'},
        {nombre: 'AC'},
        {nombre: 'Rines'},
        {nombre: 'BolsaAire'},
        {nombre: 'CierreCentralizado'},
        {nombre: 'Mecanico'},
        {nombre: 'RetrovisorElectronico'},
        {nombre: 'Overfenders'},
        {nombre: 'ColaPato'},
        {nombre: 'CintaDecorativa'},
        {nombre: 'LicenciaEstado'},
        {nombre: 'ObservacionesFinales'},
        {nombre: 'RefTipoSolicitanteInformeAjusteId'},
        {nombre: 'TipoAcuerdoFicohsa'},
        {nombre: 'DondeSeEncuentraVehiculo'},
        {nombre: 'NumeroUnidad'},
        {nombre: 'Parentesco'},
        {nombre: 'FechaNacimientoConductor'},
        {nombre: 'CulpableCompromisoPago'},
        {nombre: 'ObservacionCompromisoPago'},
        {nombre: 'PorqueNoUsoServicioAsistencia'},
        {nombre: 'Kilometraje'},
        {nombre: 'Motor'},
        {nombre: 'OtrosTalleres'}
      
]

// required-data
export const requiredDataAjustador = [
    /*{name:'person', titulo: 'Datos Solicitante', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-solicitante'} */
    // Datos del solicitante (segmento-solicitante, índice 0 en segments_aju).
    {nombre: 'RefTipoSolicitanteInformeAjusteId', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-solicitante', segmentIndex: 0, requerido: true, etiqueta: 'Tipo de Solicitante', categoria: 'ajustador', storageKey: 'tipoSolicitante'},
    {nombre: 'TipoAcuerdoFicohsa', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-solicitante', segmentIndex: 0, requerido: true, etiqueta: 'Tipo de Cobertura', categoria: 'ajustador', storageKey: 'coberturaId'},
    {nombre: 'Nombre', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-solicitante', segmentIndex: 0, requerido: true, etiqueta: 'Nombre del asegurado', categoria: 'ajustador', storageKey: 'elNombreCliente'},
    {nombre: 'RefTipoLicenciaId', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-solicitante', segmentIndex: 0, requerido: true, etiqueta: 'Tipo de licencia', categoria: 'ajustador', storageKey: 'elTipoLicencia'},
    {nombre: 'Sexo', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-solicitante', segmentIndex: 0, requerido: true, etiqueta: 'Tipo de género', categoria: 'ajustador', storageKey: 'elGenero'},
    {nombre: 'Parentesco', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-solicitante', segmentIndex: 0, requerido: true, etiqueta: 'Tipo de parentesco', categoria: 'ajustador', storageKey: 'elParentesco'},
    //{nombre: 'Kilometraje', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-solicitante', segmentIndex: 1, requerido: true, etiqueta: 'Kilometraje', categoria: 'ajustador', storageKey: 'elKilometraje'},
    {nombre: 'Kilometraje', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-vehiculo', segmentIndex: 1, requerido: true, etiqueta: 'Kilometraje', categoria: 'ajustador', storageKey: 'elKilometraje'},
    {nombre: 'RefTipoCombustibleId', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-caracteristicas', segmentIndex: 2, requerido: true, etiqueta: 'Tipo de Combustible', categoria: 'ajustador', storageKey: 'elTipoCombustible'},
    {nombre: 'AC', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-caracteristicas', segmentIndex: 2, requerido: true, etiqueta: 'Aire Acondicionado', categoria: 'ajustador', storageKey: 'elAC'},
    {nombre: 'Rines', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-caracteristicas', segmentIndex: 2, requerido: true, etiqueta: 'Rines', categoria: 'ajustador', storageKey: 'losRines'},
    {nombre: 'BolsaAire', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-caracteristicas', segmentIndex: 2, requerido: true, etiqueta: 'Bolsa de Aire', categoria: 'ajustador', storageKey: 'elBA'},
    {nombre: 'CierreCentralizado', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-caracteristicas', segmentIndex: 2, requerido: true, etiqueta: 'Cierre Centralizado', categoria: 'ajustador', storageKey: 'elCentra'},
    {nombre: 'Mecanico', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-caracteristicas', segmentIndex: 2, requerido: true, etiqueta: 'Mecánico', categoria: 'ajustador', storageKey: 'datos-Mecanico'},
    {nombre: 'ValorReserva', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-danio', segmentIndex: 3, requerido: true, etiqueta: 'Valor de Reserva', categoria: 'ajustador', storageKey: 'bpmArray-ValorReserva'},
    {nombre: 'RetrovisorElectronico', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-caracteristicas', segmentIndex: 2, requerido: true, etiqueta: 'Retrovisor Electrónico', categoria: 'ajustador', storageKey: 'elRetrovisor'},
    {nombre: 'Overfenders', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-caracteristicas', segmentIndex: 2, requerido: true, etiqueta: 'Overfenders', categoria: 'ajustador', storageKey: 'elOverfender'},
    {nombre: 'ColaPato', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-caracteristicas', segmentIndex: 2, requerido: true, etiqueta: 'Cola De Pato', categoria: 'ajustador', storageKey: 'laColaPato'},
    {nombre: 'CintaDecorativa', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-caracteristicas', segmentIndex: 2, requerido: true, etiqueta: 'Cinta Decorativa', categoria: 'ajustador', storageKey: 'laCinta'},
    {nombre: 'ObservacionesFinales', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-danio', segmentIndex: 3, requerido: true, etiqueta: 'Observaciones Finales', categoria: 'ajustador', storageKey: 'lasObservaciones'},
    {nombre: 'Observaciones', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-danio', segmentIndex: 3, requerido: true, etiqueta: 'Observaciones', categoria: 'ajustador', storageKey: 'laObservacionTaller'},
    {nombre: 'TallerMecanicoId', idSegmento: 'segmentRequestAju', pagSegmento: 'segmento-caracteristicas', segmentIndex: 2, requerido: true, etiqueta: 'Taller', categoria: 'ajustador', storageKey: 'elTallerId'},
]

export const requiredDataCliente = [
    {nombre: 'AseguradoUsoPoliza', requerido: true, etiqueta: 'Usó Póliza', categoria: 'cliente', segmentoId: 'segmentCoordinates', inputIndex: 0, segmentIndex: 0, segmentKey: 'location', storageKey: 'elAseguradoUsoPoliza'},
    {nombre: 'Cliente', requerido: true, etiqueta: 'Cliente', categoria: 'cliente', segmentoId: 'segmentAfiliated', inputIndex: 1, segmentIndex: 1, segmentKey: 'person', storageKey: 'elNombreCliente'},
    {nombre: 'Poliza', requerido: true, etiqueta: 'Póliza', categoria: 'cliente', segmentoId: 'segmentAfiliated', inputIndex: 2, segmentIndex: 1, segmentKey: 'person', storageKey: 'laPoliza'},
    {nombre: 'DireccionEnvioCorrespondencia', requerido: true, etiqueta: 'Dirección Envío Correspondencia', categoria: 'cliente', segmentoId: 'segmentAfiliated', inputIndex: 4, segmentIndex: 1, segmentKey: 'person', storageKey: 'laDireccionEnmvio'},
    {nombre: 'CorreoElectronico', requerido: true, etiqueta: 'Correo Electrónico', categoria: 'cliente', segmentoId: 'segmentAfiliated', inputIndex: 3, segmentIndex: 1, segmentKey: 'person', storageKey: 'elCorreoElectronico'},
    {nombre: 'FechaHora', requerido: true, etiqueta: 'Fecha Hora Siniestro', categoria: 'cliente', segmentoId: 'segmentAfiliated', inputIndex: 4, segmentIndex: 1, segmentKey: 'person', storageKey: 'laFechaHora'},    
    {nombre: 'MarcaVehiculo', requerido: true, etiqueta: 'Marca Vehículo', categoria: 'cliente', segmentoId: 'segmentVehicle', inputIndex: 5, segmentIndex: 2, segmentKey: 'car-sport', storageKey: 'laMarcaVehiculo'},
    {nombre: 'ModeloVehiculo', requerido: true, etiqueta: 'Modelo Vehículo', categoria: 'cliente', segmentoId: 'segmentVehicle', inputIndex: 6, segmentIndex: 2, segmentKey: 'car-sport', storageKey: 'elModeloVehiculo'},
    {nombre: 'AnioVehiculo', requerido: true, etiqueta: 'Año Vehículo', categoria: 'cliente', segmentoId: 'segmentVehicle', inputIndex: 7, segmentIndex: 2, segmentKey: 'car-sport', storageKey: 'elAnioVehiculo'},
    {nombre: 'ChasisVehiculo', requerido: true, etiqueta: 'Chasis Vehículo', categoria: 'cliente', segmentoId: 'segmentVehicle', inputIndex: 8, segmentIndex: 2, segmentKey: 'car-sport', storageKey: 'elChasisVehiculo'},
    {nombre: 'PlacaVehiculo', requerido: true, etiqueta: 'Placa Vehículo', categoria: 'cliente', segmentoId: 'segmentVehicle', inputIndex: 9, segmentIndex: 2, segmentKey: 'car-sport', storageKey: 'laPlacaVehiculo'},
    {nombre: 'NumeroUnidad', requerido: true, etiqueta: 'Número de Unidad', segmentoId: 'segmentVehicle', inputIndex: 10, segmentIndex: 2, segmentKey: 'car-sport', storageKey: 'elNumeroUnidad'},
    {nombre: 'NombreConductor', requerido: true, etiqueta: 'Nombre Conductor', categoria: 'cliente', segmentoId: 'segmentDriver', inputIndex: 11, segmentIndex: 3, segmentKey: 'speedometer', storageKey: 'elNombreCliente'},
    //{nombre: 'IdentidaConductor', requerido: true, etiqueta: 'Identidad Conductor', categoria: 'cliente', segmentoId: 'segmentDriver', inputIndex: 12, segmentIndex: 3, segmentKey: 'speedometer', storageKey: 'laIdentidadCliente'},
    {nombre: 'FechaNacimientoConductor', requerido: true, etiqueta: 'Fecha Nacimiento Conductor', categoria: 'cliente', segmentoId: 'segmentDriver', inputIndex: 13, segmentIndex: 3, segmentKey: 'speedometer', storageKey: 'laFechaNacimientoConductor'},
    {nombre: 'Parentesco', requerido: true, etiqueta: 'Parentesco', categoria: 'cliente', segmentoId: 'segmentDriver', inputIndex: 14, segmentIndex: 3, segmentKey: 'speedometer', storageKey: 'elParentesco'},
    {nombre: 'TipoLicencia', requerido: true, etiqueta: 'Tipo Licencia', categoria: 'cliente', segmentoId: 'segmentDriver', inputIndex: 23, segmentIndex: 3, segmentKey: 'speedometer', storageKey: 'elTipoLicencia'},
    {nombre: 'Licencia', requerido: true, etiqueta: 'Licencia', categoria: 'cliente', segmentoId: 'segmentDriver', inputIndex: 15, segmentIndex: 3, segmentKey: 'speedometer', storageKey: 'laLicencia'},
    {nombre: 'Vigencia', requerido: true, etiqueta: 'Fecha de Vencimiento', categoria: 'cliente', segmentoId: 'segmentDriver', inputIndex: 16, segmentIndex: 3, segmentKey: 'speedometer', storageKey: 'laVigencia'},
    {nombre: 'DireccionConductor', requerido: true, etiqueta: 'Dirección Conductor', categoria: 'cliente', segmentoId: 'segmentDriver', inputIndex: 17, segmentIndex: 3, segmentKey: 'speedometer', storageKey: 'laDireccionConductor'},
    {nombre: 'TelefonoConductor', requerido: true, etiqueta: 'Teléfono Conductor', categoria: 'cliente', segmentoId: 'segmentDriver', inputIndex: 18, segmentIndex: 3, segmentKey: 'speedometer', storageKey: 'elTelefonoOrigen'},
    {nombre: 'CelularConductor', requerido: true, etiqueta: 'Celular Conductor', categoria: 'cliente', segmentoId: 'segmentDriver', inputIndex: 19, segmentIndex: 3, segmentKey: 'speedometer', storageKey: 'elTelefonoOrigen'},
    {nombre: 'NombreAtribuyeAccidente', requerido: true, etiqueta: 'Nombre Del Responsable', categoria: 'cliente', segmentoId: 'segmentInfo', inputIndex: 20, segmentIndex: 4, segmentKey: 'help-circle', storageKey: 'elNombreAtribuyeAccidente'},
    {nombre: 'AutoridadInvolucrada', requerido: true, etiqueta: 'Autoridad Involucrada', categoria: 'cliente', segmentoId: 'segmentInfo', inputIndex: 21, segmentIndex: 4, segmentKey: 'help-circle', storageKey: 'laAutoridadInvolucrada'},
    {nombre: 'DondeSeEncuentraVehiculo', requerido: true, etiqueta: 'Dónde Se Encuentra El Vehículo', categoria: 'cliente', segmentoId: 'segmentInfo', inputIndex: 22, segmentIndex: 4, segmentKey: 'help-circle', storageKey: 'elDondeSeEncuentraVehiculo'},
    {nombre: 'UbicacionVehiculoDetenido', requerido: true, etiqueta: 'Ubicación Vehículo Detenido', categoria: 'cliente', segmentoId: 'segmentInfo', inputIndex: 23, segmentIndex: 4, segmentKey: 'help-circle', storageKey: 'laUbicacionVehiculoDetenido'},
    {nombre: 'DescripcionDanio', requerido: true, etiqueta: 'Descripción Daño', categoria: 'cliente', segmentoId: 'segmentInfo', inputIndex: 24, segmentIndex: 4, segmentKey: 'help-circle', storageKey: 'laDescripcion'},
    {nombre: 'RefAtencionId', requerido: true, etiqueta: 'Id de Atención', categoria: 'cliente', segmentoId: '', inputIndex: 0, segmentIndex: 25, segmentKey: '', storageKey: 'laRefAtencionId'},
]

export const requiredData = [
    {nombre: 'Poliza', requerido: true, etiqueta: 'Póliza', categoria: 'cliente', storageKey: 'laPoliza'},
    {nombre: 'Cliente', requerido: true, etiqueta: 'Cliente', categoria: 'cliente', storageKey: 'elNombreCliente'},
    {nombre: 'DireccionEnvioCorrespondencia', requerido: true, etiqueta: 'Dirección Envío Correspondencia', categoria: 'cliente', storageKey: 'laDireccionEnmvio'},
    {nombre: 'FechaHora', requerido: true, etiqueta: 'Fecha Hora Siniestro', categoria: 'cliente', storageKey: 'laFechaHora'},
    {nombre: 'AseguradoUsoPoliza', requerido: true, etiqueta: 'Usó Póliza', categoria: 'cliente', storageKey: 'elAseguradoUsoPoliza'},
    {nombre: 'MarcaVehiculo', requerido: true, etiqueta: 'Marca Vehículo', categoria: 'cliente', storageKey: 'laMarcaVehiculo'},
    {nombre: 'ModeloVehiculo', requerido: true, etiqueta: 'Modelo Vehículo', categoria: 'cliente', storageKey: 'elModeloVehiculo'},
    {nombre: 'AnioVehiculo', requerido: true, etiqueta: 'Año Vehículo', categoria: 'cliente', storageKey: 'elAnioVehiculo'},
    {nombre: 'PlacaVehiculo', requerido: true, etiqueta: 'Placa Vehículo', categoria: 'cliente', storageKey: 'laPlacaVehiculo'},
    {nombre: 'ChasisVehiculo', requerido: true, etiqueta: 'Chasis Vehículo', categoria: 'cliente', storageKey: 'elChasisVehiculo'},
    {nombre: 'NumeroUnidad', requerido: true, etiqueta: 'Número de Unidad', storageKey: 'elNumeroUnidad'},
    {nombre: 'NombreConductor', requerido: true, etiqueta: 'Nombre Conductor', categoria: 'cliente', storageKey: 'elNombreCliente'},
    {nombre: 'Parentesco', requerido: true, etiqueta: 'Parentesco', categoria: 'cliente', storageKey: 'elParentesco'},
    {nombre: 'IdentidaConductor', requerido: true, etiqueta: 'Identidad Conductor', categoria: 'cliente', storageKey: 'laIdentidadCliente'},
    {nombre: 'FechaNacimientoConductor', requerido: true, etiqueta: 'Fecha Nacimiento Conductor', categoria: 'cliente', storageKey: 'laFechaNacimientoConductor'},
    {nombre: 'TipoLicencia', requerido: true, etiqueta: 'Tipo Licencia', categoria: 'cliente', storageKey: 'elTipoLicencia'},
    {nombre: 'Licencia', requerido: true, etiqueta: 'Licencia', categoria: 'cliente', storageKey: 'laLicencia'},
    {nombre: 'Vigencia', requerido: true, etiqueta: 'Fecha de Vencimiento', categoria: 'cliente', storageKey: 'laVigencia'},
    {nombre: 'DireccionConductor', requerido: true, etiqueta: 'Dirección Conductor', categoria: 'cliente', storageKey: 'laDireccionConductor'},
    {nombre: 'TelefonFijo', requerido: true, etiqueta: 'Teléfono Conductor', categoria: 'cliente', storageKey: 'elTelefonoOrigen'},
    {nombre: 'CelularConductor', requerido: true, etiqueta: 'Celular Conductor', categoria: 'cliente', storageKey: 'elTelefonoOrigen'},
    {nombre: 'NombreAtribuyeAccidente', requerido: true, etiqueta: 'Nombre Del Responsable', categoria: 'cliente', storageKey: 'elNombreAtribuyeAccidente'},
    {nombre: 'AutoridadInvolucrada', requerido: true, etiqueta: 'Autoridad Involucrada', categoria: 'cliente', storageKey: 'laAutoridadInvolucrada'},
    {nombre: 'DondeSeEncuentraVehiculo', requerido: true, etiqueta: 'Dónde Se Encuentra El Vehículo', categoria: 'cliente', storageKey: 'elDondeSeEncuentraVehiculo'},
    {nombre: 'UbicacionVehiculoDetenido', requerido: true, etiqueta: 'Ubicación Vehículo Detenido', categoria: 'cliente', storageKey: 'laUbicacionVehiculoDetenido'},
    {nombre: 'DescripcionDanio', requerido: true, etiqueta: 'Descripción Daño', categoria: 'cliente', storageKey: 'laDescripcion'},
    {nombre: 'CorreoElectronico', requerido: true, etiqueta: 'Correo Electrónico', categoria: 'cliente', storageKey: 'elCorreoElectronico'},
    {nombre: 'RefAtencionId', requerido: true, etiqueta: 'Id de Atención', categoria: 'cliente', storageKey: 'laRefAtencionId'},

    {nombre: 'RefTipoSolicitanteInformeAjusteId', requerido: true, etiqueta: 'Tipo De Solicitante', categoria: 'ajustador', storageKey: 'tipoSolicitante'},
    {nombre: 'Kilometraje', requerido: true, etiqueta: 'Kilometraje', categoria: 'ajustador', storageKey: 'elKilometraje'},
    {nombre: 'RefTipoCombustibleId', requerido: true, etiqueta: 'Tipo de Combustible', categoria: 'ajustador', storageKey: 'elTipoCombustible'},
    {nombre: 'AC', requerido: true, etiqueta: 'Aire Acondicionado', categoria: 'ajustador', storageKey: 'elAC'},
    {nombre: 'Rines', requerido: true, etiqueta: 'Rines', categoria: 'ajustador', storageKey: 'losRines'},
    {nombre: 'BolsaAire', requerido: true, etiqueta: 'Bolsa de Aire', categoria: 'ajustador', storageKey: 'elBA'},
    {nombre: 'CierreCentralizado', requerido: true, etiqueta: 'Cierre Centralizado', categoria: 'ajustador', storageKey: 'elCentra'},
    {nombre: 'Mecanico', requerido: true, etiqueta: 'Mecánico', categoria: 'ajustador', storageKey: 'datos-Mecanico'},
    {nombre: 'ValorReserva', requerido: true, etiqueta: 'Valor de Reserva', categoria: 'ajustador', storageKey: 'bpmArray-ValorReserva'},
    {nombre: 'RetrovisorElectronico', requerido: true, etiqueta: 'Retrovisor Electrónico', categoria: 'ajustador', storageKey: 'elRetrovisor'},
    {nombre: 'Overfenders', requerido: true, etiqueta: 'Overfenders', categoria: 'ajustador', storageKey: 'elOverfender'},
    {nombre: 'ColaPato', requerido: true, etiqueta: 'Cola De Pato', categoria: 'ajustador', storageKey: 'laColaPato'},
    {nombre: 'CintaDecorativa', requerido: true, etiqueta: 'Cinta Decorativa', categoria: 'ajustador', storageKey: 'laCinta'},
    {nombre: 'LicenciaEstado', requerido: true, etiqueta: 'Estado De La Licencia', categoria: 'cliente', storageKey: 'laLicenciaEstado'},
    {nombre: 'ObservacionesFinales', requerido: true, etiqueta: 'Observaciones Finales', categoria: 'ajustador', storageKey: 'lasObservaciones'},
    {nombre: 'Observaciones', requerido: true, etiqueta: 'Observaciones', categoria: 'ajustador', storageKey: 'laObservacionTaller'},
    {nombre: 'TallerMecanicoId', requerido: true, etiqueta: 'Taller', categoria: 'ajustador', storageKey: 'elTallerId'},
]

export const requiredData_Less = [
    {nombre: 'Poliza', requerido: true, etiqueta: 'Póliza', categoria: 'cliente', storageKey: 'laPoliza'},
    {nombre: 'Cliente', requerido: true, etiqueta: 'Cliente', categoria: 'cliente', storageKey: 'elNombreCliente'},
    {nombre: 'FechaHora', requerido: true, etiqueta: 'Fecha Hora Siniestro', categoria: 'cliente', storageKey: 'laFechaHora'},
    {nombre: 'AseguradoUsoPoliza', requerido: true, etiqueta: 'Usó Póliza', categoria: 'cliente', storageKey: 'elAseguradoUsoPoliza'},
    {nombre: 'MarcaVehiculo', requerido: true, etiqueta: 'Marca Vehículo', categoria: 'cliente', storageKey: 'laMarcaVehiculo'},
    {nombre: 'ModeloVehiculo', requerido: true, etiqueta: 'Modelo Vehículo', categoria: 'cliente', storageKey: 'elModeloVehiculo'},
    {nombre: 'AnioVehiculo', requerido: true, etiqueta: 'Año Vehículo', categoria: 'cliente', storageKey: 'elAnioVehiculo'},
    {nombre: 'PlacaVehiculo', requerido: true, etiqueta: 'Placa Vehículo', categoria: 'cliente', storageKey: 'laPlacaVehiculo'},
    {nombre: 'ChasisVehiculo', requerido: true, etiqueta: 'Chasis Vehículo', categoria: 'cliente', storageKey: 'elChasisVehiculo'},
    {nombre: 'NombreConductor', requerido: true, etiqueta: 'Nombre Conductor', categoria: 'cliente', storageKey: 'elNombreCliente'},
    {nombre: 'RefAtencionId', requerido: true, etiqueta: 'Id de Atención', categoria: 'cliente', storageKey: 'laRefAtencionId'},
]

export const requiredData_NOP = [
    {nombre: 'TipoAcuerdoFicohsa'},
    {nombre: 'NombreConductor'},
    {nombre: 'elTipoGenero'},
]

export const actionButtons = [
    {title: 'Materiales', icon: '../../assets/img/arrive6.svg'},
    {title: 'Chat', icon: '../../assets/img/arrive5.svg'},
    {title: 'Calificar', icon: '../../assets/img/arrive4.svg'},
    {title: 'Marcar contacto', icon: '../../assets/img/arrive3.svg'},
    {title: 'En arribo', icon: '../../assets/img/arrive2.svg'},
    {title: 'Acciones', icon: '../../assets/img/action1.svg'}
]

export const requiredDataLabels = [
    {etiqueta: 'Póliza'},
    {etiqueta: 'Cliente'},
    {etiqueta: 'Dirección Envío Correspondencia'},
    {etiqueta: 'Teléfono Conductor'},
    {etiqueta: 'Celular Conductor'},
    {etiqueta: 'Correo Electrónico'},
    {etiqueta: 'Fecha Hora Siniestro'},
    {etiqueta: 'Usó Póliza'},
    {etiqueta: 'Marca Vehículo'},
    {etiqueta: 'Modelo Vehículo'},
    {etiqueta: 'Año Vehículo'},
    {etiqueta: 'Placa Vehículo'},
    {etiqueta: 'Chasis Vehículo'},
    {etiqueta: 'Motor Vehículo'}, // No hay campo que reciba este dato en el backend
    {etiqueta: 'Número Unidad'}, // Preguntar cuando no tienen numero de unidad como tratar el required
    {etiqueta: 'Nombre Conductor'},
    {etiqueta: 'Parentesco'},
    {etiqueta: 'Identidad Conductor'},
    {etiqueta: 'Fecha Nacimiento Conductor'},
    {etiqueta: 'Tipo Licencia'},
    {etiqueta: 'Licencia'},
    {etiqueta: 'Vigencia'},
    {etiqueta: 'Dirección Conductor'},
    {etiqueta: 'Teléfono Conductor'},
    {etiqueta: 'Celular Conductor'},
    {etiqueta: 'Nombre Del Responsable'},
    {etiqueta: 'Autoridad Involucrada'},
    {etiqueta: 'Dónde Se Encuentra El Vehículo'},
    {etiqueta: 'Ubicación Vehículo Detenido'},
    {etiqueta: 'Descripción Daño'},
    {etiqueta: 'Tipo De Solicitante'},
    {etiqueta: 'Nombre'}, // Nombre del solicitante? No hay campo que reciba este dato en el backend
    {etiqueta: 'Correo Electrónico'},
    {etiqueta: 'Teléfono Solicitante'}, // No hay campo que reciba este dato en el backend
    {etiqueta: 'Fecha Siniestro'}, // FechaHora? No hay campo que reciba este dato en el backend
    {etiqueta: 'Fecha Inspección'}, // No hay campo que reciba este dato en el backend
    {etiqueta: 'Id de Atención'},
    {etiqueta: 'Kilometraje'},
    {etiqueta: 'Tipo de Combustible'},
    {etiqueta: 'Aire Acondicionado'},
    {etiqueta: 'Rines'},
    {etiqueta: 'Bolsa de Aire'},
    {etiqueta: 'Cierre Centralizado'},
    {etiqueta: 'Mecánico'},
    {etiqueta: 'Retrovisor Electrónico'},
    {etiqueta: 'Overfenders'},
    {etiqueta: 'Cola De Pato'},
    {etiqueta: 'Cinta Decorativa'},
    {etiqueta: 'Estado De La Licencia'},
    {etiqueta: 'Observaciones Finales'},
    {etiqueta: 'Observaciones'},
    {etiqueta: 'Daños'},
    {etiqueta: 'Taller'},
    {etiqueta: 'Dirección Culpable'},
    {etiqueta: 'Código De Reclamo'},
]

export const adeudaEtiquetas = [
    
        {etiqueta: "Id"},
        {etiqueta: "NombreDeudor"},
        {etiqueta: "IdentidadDeudor"},
        {etiqueta: "Celular"},
        {etiqueta: "Domicilio"},
        {etiqueta: "CorreoElectronico"},
        {etiqueta: "LugarDeTrabajo"},
        {etiqueta: "NombreContacto"},
        {etiqueta: "CelularContacto"},
        {etiqueta: "FechaRegistroDocumento"},
        {etiqueta: "Marca"},
        {etiqueta: "Modelo"},
        {etiqueta: "Anio"},
        {etiqueta: "Placa"},
        {etiqueta: "NombreAsegurado"},
        {etiqueta: "MarcaImplicado"},
        {etiqueta: "ModeloImplicado"},
        {etiqueta: "AnioImplicado"},
        {etiqueta: "PlacaImplicado"},
        {etiqueta: "NombrePersonaPropiedadImplicada"},
        {etiqueta: "DanioCausadoObservacion"},
        {etiqueta: "RefAtencionId"},
        {etiqueta: "FechaRegistro"},
        {etiqueta: "FirmaDeudor"},
        {etiqueta: "Ciudad"},
        {etiqueta: "TelefonoCulpable"},
        {etiqueta: "LicenciaCulpable"},
        {etiqueta: "TipoLicencia"},
        {etiqueta: "FechaVencimientoLicencia"},
        {etiqueta: "NombreDireccionPropietarioVehiculoImplicado"},
        {etiqueta: "CompromisoDePago"},
        {etiqueta: "Observaciones"},
        {etiqueta: "Edad"},
        {etiqueta: "RefTipoFotografiaIdAdeudado"},
        {etiqueta: "RefTipoFotografiaIdBeneficiario"}
      
]


export const tipoBeneficiario = [
    {tipo:1, etiqueta:'Asegurado'},
    {tipo:2, etiqueta:'Beneficiario'},
    {tipo:3, etiqueta:'Tercero'}
]

export const tiposDeReparacion = [
    {tipo:1, etiqueta:'Reparacion'},
    {tipo:2, etiqueta:'Cambio'},
    {tipo:3, etiqueta:'No Reparar'}
]

export const cacheIndexArray = [
    
        {title:'IdAtencion'},
        {title:'Nombre'},
        {title:'AutoridadInvolucrada'},
        {title:'NombreConductor'},
        {title:'IdentidaConductor'},
        {title:'Poliza'},
        {title:'NombreAtribuyeAccidente'},
        {title:'TelefonoConductor'},
        {title:'CelularConductor'},
        {title:'CorreoElectronico'},
        {title:'Licencia'},
        {title:'Blindado'},
        {title:'FechaNacimientoConductor'},
        {title:'Edad'},
        {title:'AseguradoUsoPoliza'},
        {title:'PorqueNoUsoServicioAsistencia'},
        {title:'PruebaAlcoholemia'},
        {title:'AgendarAudiencia'},
        {title:'VehiculoDetenido'},
        {title:'ConductorDetenido'},
        {title:'VehiculoVolcado'},
        {title:'DireccionEnvioCorrespondencia'},
        {title:'DireccionConductor'},
        {title:'DondeSeEncuentraVehiculo'},
        {title:'TerceroResponsable'},
        {title:'UbicacionVehiculoDetenido'},
        {title:'DescripcionAudiencia'},
        {title:'LicenciaEstado'},
        {title:'Vigencia'},
        {title:'RefTipoLicenciaId'},
        {title:'TipoLicencia'},
        {title:'NumeroUnidad'},
        {title:'DescripcionTercerosMuertos'},
        {title:'DescripcionTercerosHeridos'},
        {title:'Descripcion'},
        {title:'DescripcionDanio'},
        {title:'RefTipoConductorId'},
        {title:'TercerosMuertos'},
        {title:'TercerosHeridos'},
        {title:'Parentesco'},
        {title:'Latitud'},
        {title:'Longitud'},
        {title:'AnioVehiculo'},
        {title:'ModeloVehiculo'},
        {title:'PlacaVehiculo'},
        {title:'ColorVehiculo'},
        {title:'MarcaVehiculo'},
        {title:'ChasisVehiculo'},
        {title:'Motor'}
      
]
export const valoresPredeterminados = [
    {
      puntoServicio: "307",
      Sucursal: "0001",
      Producto: "AU01",
      Ramo: "0002",
      Causa: "A001"
    }
  ]

